# Generated by Django 4.1.2 on 2022-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pic1",
            field=models.ImageField(default="", null=True, upload_to="upload"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic2",
            field=models.ImageField(default="", null=True, upload_to="upload"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic3",
            field=models.ImageField(default="", null=True, upload_to="upload"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic4",
            field=models.ImageField(default="", null=True, upload_to="upload"),
        ),
    ]
